# Generated by Django 5.0 on 2024-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial')], max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('partial_area', models.CharField(blank=True, choices=[('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('hallway', 'Hallway'), ('exterior', 'Exterior')], max_length=50, null=True)),
                ('start_date', models.DateTimeField()),
                ('budget_category', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
