# Generated by Django 5.0 on 2024-12-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='partial_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='cost_calculator.housepart'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='cost_calculator.housepart')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_works', to='cost_calculator.project')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='cost_calculator.work')),
            ],
        ),
    ]
