# Generated by Django 5.0 on 2024-12-20 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0004_projectwork_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='house_part',
        ),
        migrations.AddField(
            model_name='project',
            name='tart_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='work',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='housepart',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='partial_area',
            field=models.CharField(blank=True, choices=[('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('hallway', 'Hallway'), ('exterior', 'Exterior')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
