# Generated by Django 5.0 on 2024-12-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0006_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwork',
            name='total_cost',
        ),
    ]
