# Generated by Django 5.0 on 2024-12-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0008_craftsman_remove_material_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description available')),
            ],
        ),
        migrations.AlterField(
            model_name='housepart',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_in_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('house_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cost_calculator.housepart')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cost_calculator.roomtype')),
            ],
        ),
    ]
