# Generated by Django 5.0 on 2024-12-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0009_roomtype_alter_housepart_description_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
        migrations.RenameField(
            model_name='materialusage',
            old_name='task',
            new_name='tasks',
        ),
    ]
