# Generated by Django 5.0 on 2024-12-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0010_rename_task_tasks_rename_task_materialusage_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialusage',
            name='tasks',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('craftsman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_calculator.craftsman')),
                ('house_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='cost_calculator.housepart')),
            ],
        ),
        migrations.AddField(
            model_name='materialusage',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cost_calculator.task'),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
