# Generated by Django 5.0 on 2024-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0012_remove_task_estimated_hours_alter_task_house_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.IntegerField(default=0),
        ),
    ]
