# Generated by Django 5.0 on 2024-12-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0013_task_estimated_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='craftsman',
        ),
        migrations.RemoveField(
            model_name='room',
            name='house_part',
        ),
        migrations.RemoveField(
            model_name='task',
            name='house_part',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='task',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='Craftsman',
        ),
        migrations.DeleteModel(
            name='HousePart',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialUsage',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
